version: '3'

services:

  basket.api:
    image: niyuen.azurecr.io/eshop/basket.api:${TAG:-latest}
    build:
      context: ./src/Services/Basket/Basket.API
      dockerfile: Dockerfile    
    depends_on:
      - basket.data
      - identity.api
      - rabbitmq

  catalog.api:
    image: niyuen.azurecr.io/eshop/catalog.api:${TAG:-latest}
    build:
      context: ./src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  identity.api:
    image: niyuen.azurecr.io/eshop/identity.api:${TAG:-latest}
    build:
      context: ./src/Services/Identity/Identity.API
      dockerfile: Dockerfile    
    depends_on:
      - sql.data

  ordering.api:
    image: niyuen.azurecr.io/eshop/ordering.api:${TAG:-latest}
    build:
      context: ./src/Services/Ordering/Ordering.API
      dockerfile: Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  marketing.api:
    image: niyuen.azurecr.io/eshop/marketing.api:${TAG:-latest}
    build:
      context: ./src/Services/Marketing/Marketing.API
      dockerfile: Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  webspa:
    image: niyuen.azurecr.io/eshop/webspa:${TAG:-latest}
    build:
      context: ./src/Web/WebSPA
      dockerfile: Dockerfile    
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api

  webmvc:
    image: niyuen.azurecr.io/eshop/webmvc:${TAG:-latest}
    build:
      context: ./src/Web/WebMVC
      dockerfile: Dockerfile    
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api

  webstatus:
    image: niyuen.azurecr.io/eshop/webstatus:${TAG:-latest}
    build:
      context: ./src/Web/WebStatus
      dockerfile: Dockerfile

  payment.api:
    image: niyuen.azurecr.io/eshop/payment.api:${TAG:-latest}
    build:
      context: ./src/Services/Payment/Payment.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq    
    
  locations.api:
    image: niyuen.azurecr.io/eshop/locations.api:${TAG:-latest}
    build:
      context: ./src/Services/Location/Locations.API
      dockerfile: Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  basket.data:
    image: redis
      
  rabbitmq:
    image: rabbitmq:3-management
